### ISSUE TITLE
OOP-1-review-2022-10-15

### ISSUE THREAD

**Issue by jakub-hamerlinski-put** [bartoszkorszun/oop-put-course#1]
**Task 1**
- [x] Proper communication/interaction between classes and objects is missing.

**Task 1 and 2**
- [x] Rename repository to **oop-put-course**
- [x] Remove unnecessary [files like](https://github.com/bartoszkorszun/ProgramowanieObiektoweLabStudia/blob/main/ObjectProgrammingLab1Exercise2/app/src/test/java/ObjectProgrammingLab1Exercise2/AppTest.java) and [comments like](https://github.com/bartoszkorszun/ProgramowanieObiektoweLabStudia/blob/main/ObjectProgrammingLab1Exercise2/app/src/main/java/ObjectProgrammingLab1Exercise2/Age.java#L1-L4)
